import rtconfig,os
from building import *

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')
src  += Glob('*.cpp')

# group = DefineGroup('TFT_LIBRARY', src, depend = [''], CPPPATH = path)
group = []



Return('group')
