import rtconfig, os
from building import *

cwd = GetCurrentDir()
path = [cwd, cwd + "/driver"]
src = Glob("*.c")
src += Glob("*.cpp")

if GetDepend(["DRIVER_USING_R61581"]):
    src += Glob("driver/r61581.cpp")

if GetDepend(["DRIVER_USING_ILI9341"]):
    src += Glob("driver/r61581.cpp")


group = DefineGroup("TFT", src, depend=[""], CPPPATH=path)


Return("group")
