import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Glob('*.c')
src += Glob('port/*.c')
src += Glob('core/*.c')

# # add cubemx drivers
# src += Split('''
# CubeMX_Config/Core/Src/stm32h7xx_hal_msp.c
# ''')

path = [cwd]
path += [cwd + '/port']
path += [cwd + '/core']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
