import rtconfig
from building import *

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')
src  += Glob('*.cpp')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
